name: 'Helm Deploy'
description: 'Deploy Kubernetes applications using helm'
author: 'BankiFi LTD'
inputs:
  release:
    description: Helm release name. Will be combined with track if set. (required)
    required: true
  namespace:
    description: Kubernetes namespace name. (required)
    required: true
  chart:
    description: Helm chart path.
    required: true
  helm-path:
    description: Path to the helm executable
    required: false
  values:
    description: Helm chart values, expected to be a YAML or JSON string.
    required: false
  dry-run:
    description: Simulate an upgrade.
    required: false
  atomic:
    description: If true, upgrade process rolls back changes made in case of failed upgrade. Defaults to true.
    required: false
  token:
    description: Github repository token. If included and the event is a deployment
      the deployment_status event will be fired.
    required: true
    default: ${{ github.token }}
  value-files:
    description: Additional value files to apply to the helm chart. Expects JSON encoded
      array or a string.
    required: false
  secrets:
    description: Secret variables to include in value file interpolation. Expects
      JSON encoded map.
    required: false
  chart-version:
    description: The version of the helm chart you want to deploy (distinct from app version)
    required: false
  repo-url:
    description: Helm chart repository to be added.
    required: false
  repo-alias:
    description: Helm repository alias that will be used.
    required: false
  repo-username:
    description: Helm repository username if authentication is needed.
    required: false
  repo-password:
    description: Helm repository password if authentication is needed.
    required: false
  kube-config:
    description: Path to the Kubernetes configuration file
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
