name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Kube Auth
        uses: azure/aks-set-context@v2.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: baseline-sbox-uksouth
          cluster-name: baseline-sbox-aks-uksouth

      - uses: azure/setup-helm@v1
        id: helm
        with:
          version: '3.*'

      - uses: ./
        with:
          release: test
          namespace: test
          helm-path: ${{ steps.helm.outputs.helm-path }}
          chart: "bankifi/microservice"
          dry-run: true
          repo-alias: bankifi
          repo-url: https://artifacts.central.labs.bankifi.com/artifactory/helm
          repo-username: ${{ secrets.ARTIFACTORY_USERNAME }}
          repo-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          values: |
            hello: world
          value-files: >-
            [
              "./helm/test_values1.yaml",
              "./helm/test_values2.yaml"
            ]
